gallery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from users import views

app_name = 'gallery'

urlpatterns = [
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    path('account/', include('users.urls', namespace='account')),
    path('admin/', admin.site.urls),
    path('register/', views.register, name='register'),
    path('gallery/', include('images.urls'), name='gallery-images'),
    path('gallery/video/', include('videos.urls'), name='gallery-videos'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    #path('login/', views.user_login, name='login'),
    #path('logout/', views.user_logout, name='logout'),
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),

]

videos/urls.py
from django.urls import path
from videos.views import VideoList, VideoCreate, VideoDetail, VideoDelete

app_name = 'videos'

urlpatterns = [
    path('', VideoList.as_view(), name='videos-list'),
    path('create/', VideoCreate.as_view(), name='videos-create'),
    path('detail/<slug:slug>/', VideoDetail.as_view(), name='videos_detail'),
    path('delete/<int:pk>/', VideoDelete.as_view(), name='videos_delete')
]

videos/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator


# class Tag(models.Model):
#     name = models.CharField(max_length=150)
#
#     def __str__(self):
#         return self.name


class Video(models.Model):
    title = models.CharField(max_length=150)
    # tags = models.ManyToManyField(Tag, related_name='gallery_posts')
    video = models.FileField(upload_to='videos/%Y/%m/%d',
                             validators=[
                                 FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mkv', 'mov', 'wmv', 'gif'])])
    slug = models.SlugField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='video_content')

    class Meta:
        indexes = [
            models.Index(fields=['-created']),
        ]
        ordering = ['-created']

    def __str__(self):
        return self.title

videos/views.py
from django.contrib.auth.decorators import login_required
# from django.contrib.auth.mixins import PermissionRequiredMixin
# from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, CreateView, DeleteView
from .models import Video


#@method_decorator(login_required, name='dispatch')
class VideoList(ListView):
    #permission_required = ['videos.add_video', 'videos.view_video', 'videos.change_video', 'videos.delete_video']
    model = Video
    template_name = 'videos/video_list.html'
    context_object_name = 'video_list'
    paginate_by = 16


class VideoDetail(DetailView):
    model = Video
    template_name = 'videos/video_detail.html'
    slug_field = 'slug'


@method_decorator(login_required, name='dispatch')
class VideoCreate(CreateView):
    model = Video
    fields = ['title', 'video', 'slug']
    success_url = '/gallery/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class VideoDelete(DeleteView):
    model = Video
    success_url = '/gallery/'
    template_name = 'videos/video_confirm_delete.html'

templates/videos/video_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete</title>
</head>
<body>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>
</body>
</html>

templates/videos/video_detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Video Detail</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo-style.css' %}">


</head>
<body>
    <!-- Page Loader -->
    <div id="loader-wrapper">
        <div id="loader"></div>

        <div class="loader-section section-left"></div>
        <div class="loader-section section-right"></div>

    </div>
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand" href="/gallery">
                <i class="fas fa-film mr-2"></i>
                Album
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a href="/create/" role="button" class="btn btn-primary">Add</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-link-1" href="/gallery">Photos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-link-2 active" aria-current="page" href="/gallery/video">Videos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-link-3" href="about.html">Audios</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-link-4" href="/logout">Log Out</a>
                </li>
            </ul>
            </div>
        </div>
    </nav>

    <div class="tm-hero d-flex justify-content-center align-items-center" data-parallax="scroll" data-image-src="img/hero.jpg">
        <form class="d-flex tm-search-form">
            <input class="form-control tm-search-input" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success tm-search-btn" type="submit">
                <i class="fas fa-search"></i>
            </button>
        </form>
    </div>

    <div class="container-fluid tm-container-content tm-mt-60">
        <div class="row mb-4">
            <h2 class="col-12 tm-text-primary">{{video.title}}</h2>
        </div>
        <div class="row tm-mb-90">            
            <div class="col-xl-8 col-lg-7 col-md-6 col-sm-12">
                <video autoplay muted loop controls id="tm-video" >
                    <source src="{{video.video.url}}" type="video/mp4">
                </video>  
            </div>
            <div class="col-xl-4 col-lg-5 col-md-6 col-sm-12">
                <div class="tm-bg-gray tm-video-details">
                    <div class="text-center mb-5">
                        <a href="{% url 'videos:videos_delete' video.id %}" class="btn btn-primary tm-btn-big">Delete</a>
                    </div>                    
                    <div class="mb-4 d-flex flex-wrap">
                        <div class="mr-4 mb-2">
                            <span class="tm-text-gray-dark">Format: </span><span class="tm-text-primary">MP4</span>
                        </div>
                    </div>
<!--                    <div>-->
<!--                        <h3 class="tm-text-gray-dark mb-3">Tags</h3>-->
<!--                        <a href="#" class="tm-text-primary mr-4 mb-2 d-inline-block">Cloud</a>-->
<!--                        <a href="#" class="tm-text-primary mr-4 mb-2 d-inline-block">Bluesky</a>-->
<!--                        <a href="#" class="tm-text-primary mr-4 mb-2 d-inline-block">Nature</a>-->
<!--                        <a href="#" class="tm-text-primary mr-4 mb-2 d-inline-block">Background</a>-->
<!--                        <a href="#" class="tm-text-primary mr-4 mb-2 d-inline-block">Timelapse</a>-->
<!--                        <a href="#" class="tm-text-primary mr-4 mb-2 d-inline-block">Night</a>-->
<!--                        <a href="#" class="tm-text-primary mr-4 mb-2 d-inline-block">Real Estate</a>-->
<!--                    </div>-->
                </div>
            </div>
        </div>
    </div> <!-- container-fluid, tm-container-content -->

    
    <script src="{% static 'js/plugins.js' %}"></script>
    <script>
        $(window).on("load", function() {
            $('body').addClass('loaded');
        });
    </script>
</body>
</html>

templates/videos/video_form.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo-style.css' %}">

</head>
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save">
</form>
</body>
</html>

templates/videos/video_list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Album Videos</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo-style.css' %}">


</head>
<body>
    <!-- Page Loader -->
    <div id="loader-wrapper">
        <div id="loader"></div>

        <div class="loader-section section-left"></div>
        <div class="loader-section section-right"></div>

    </div>
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand" href="/gallery">
                <i class="fas fa-film mr-2"></i>
                Album
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a href="create/" role="button" class="btn btn-primary">Add</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-link-1" href="/gallery">Photos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-link-2 active" aria-current="page" href="/gallery/video">Videos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-link-3" href="/gallery/audio">Audios</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-link-4" href="/logout">Log Out</a>
                </li>
            </ul>
            </div>
        </div>
    </nav>

    <div class="tm-hero d-flex justify-content-center align-items-center" id="tm-video-container">
<!--        <video autoplay muted loop id="tm-video">-->
<!--            <source src="video/hero.mp4" type="video/mp4">-->
<!--        </video>  -->
<!--        <i id="tm-video-control-button" class="fas fa-pause"></i>-->
        <form class="d-flex position-absolute tm-search-form">
            <input class="form-control tm-search-input" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success tm-search-btn" type="submit">
                <i class="fas fa-search"></i>
            </button>
        </form>
    </div>

    <div class="container-fluid tm-container-content tm-mt-60">
        <div class="row mb-4">
            <h2 class="col-6 tm-text-primary">
                Latest Videos
            </h2>
            <div class="col-6 d-flex justify-content-end align-items-center">
                <form action="" class="tm-text-primary">
                    Page <input type="text" value="1" size="1" class="tm-input-paging tm-text-primary"> of 180
                </form>
            </div>
        </div>
        <div class="row tm-mb-90 tm-gallery">
            {% for video in video_list %}
            <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-12 mb-5">
                <figure class="effect-ming tm-video-item">
<!--                    <video src="{{video.video.url}}" alt="Video" class="img-fluid"></video>-->
                    <video id='videoID' width="200px" height="200px" preload="true" loop="loop" muted="muted" volume="0">
                    <source src="{{video.video.url}}">
                    </video>
                    <figcaption class="d-flex align-items-center justify-content-center">
                        <h2>{{video.title}}</h2>
                        <a href="{% url 'videos:videos_detail' video.slug %}">View more</a>
                    </figcaption>                    
                </figure>
                <div class="d-flex justify-content-between tm-text-gray">
                    <span>{{video.created}}</span>
                </div>
            </div>
            {% empty %}
            <h2>No objects yet.</h2>
            {% endfor %}
        </div> <!-- row -->
        <div class="row tm-mb-90">
            <div class="col-12 d-flex justify-content-between align-items-center tm-paging-col">
                <a href="javascript:void(0);" class="btn btn-primary tm-btn-prev mb-2 disabled">Previous</a>
                <div class="tm-paging d-flex">
                    <a href="javascript:void(0);" class="active tm-paging-link">1</a>
                    <a href="javascript:void(0);" class="tm-paging-link">2</a>
                    <a href="javascript:void(0);" class="tm-paging-link">3</a>
                    <a href="javascript:void(0);" class="tm-paging-link">4</a>
                </div>
                <a href="javascript:void(0);" class="btn btn-primary tm-btn-next">Next Page</a>
            </div>            
        </div>
    </div> <!-- container-fluid, tm-container-content -->

    
    <script src="{% static 'js/plugins.js' %}"></script>
    <script>
        $(window).on("load", function() {
            $('body').addClass('loaded');
        });

        $(function(){
            /************** Video background *********/

            function setVideoSize() {
                const vidWidth = 1280;
                const vidHeight = 720;
                const maxVidHeight = 400;
                let windowWidth = window.innerWidth;
                let newVidWidth = windowWidth;
                let newVidHeight = windowWidth * vidHeight / vidWidth;
                let marginLeft = 0;
                let marginTop = 0;
            
                if (newVidHeight < maxVidHeight) {
                    newVidHeight = maxVidHeight;
                    newVidWidth = newVidHeight * vidWidth / vidHeight;
                }
            
                if(newVidWidth > windowWidth) {
                    marginLeft = -((newVidWidth - windowWidth) / 2);
                }
            
                if(newVidHeight > maxVidHeight) {
                    marginTop = -((newVidHeight - $('#tm-video-container').height()) / 2);
                }
            
                const tmVideo = $('#tm-video');
            
                tmVideo.css('width', newVidWidth);
                tmVideo.css('height', newVidHeight);
                tmVideo.css('margin-left', marginLeft);
                tmVideo.css('margin-top', marginTop);
            }

            setVideoSize();

            // Set video background size based on window size
            let timeout;
            window.onresize = function () {
                clearTimeout(timeout);
                timeout = setTimeout(setVideoSize, 100);
            };

            // Play/Pause button for video background      
            const btn = $("#tm-video-control-button");

            btn.on("click", function (e) {
                const video = document.getElementById("tm-video");
                $(this).removeClass();

                if (video.paused) {
                    video.play();
                    $(this).addClass("fas fa-pause");
                } else {
                    video.pause();
                    $(this).addClass("fas fa-play");
                }
            });
        });
    </script>
</body>
</html>