gallery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from users import views

app_name = 'gallery'

urlpatterns = [
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    path('account/', include('users.urls', namespace='account')),
    path('admin/', admin.site.urls),
    path('register/', views.register, name='register'),
    path('gallery/', include('images.urls'), name='gallery-images'),
    path('gallery/video/', include('videos.urls'), name='gallery-videos'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from images.views import ImageList, ImageCreate, ImageDetail, ImageDelete

app_name = 'images'

urlpatterns = [
    path('', ImageList.as_view(), name='images-list'),
    path('image/create/', ImageCreate.as_view(), name='images-create'),
    path('image/detail/<slug:slug>/', ImageDetail.as_view(), name='images_detail'),
    path('image/delete/<int:pk>/', ImageDelete.as_view(), name='images_delete')
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    #path('login/', views.user_login, name='login'),
    #path('logout/', views.user_logout, name='logout'),
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),

]

images/models.py
from django.db import models
from django.contrib.auth.models import User


class Image(models.Model):
    title = models.CharField(max_length=150)
    # tags = models.CharField(max_length=200)
    picture = models.ImageField(upload_to='pictures/%Y/%m/%d/', max_length=200, null=True)
    slug = models.SlugField(max_length=200, default='')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='image_content')

    class Meta:
        indexes = [
            models.Index(fields=['-created']),
        ]
        ordering = ['-created']

    def __str__(self):
        return self.title

images/views.py
from django.views.generic import ListView, DetailView, CreateView, DeleteView
from .models import Image
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


@method_decorator(login_required, name='dispatch')
class ImageList(ListView):
    #permission_required = 'images.view_image'
    model = Image
    template_name = 'images/images.html'
    context_object_name = 'image_list'
    paginate_by = 16


class ImageDetail(DetailView):
    #permission_required = ['images.view_image', 'images.delete_image']
    model = Image
    template_name = 'images/image_detail.html'
    slug_field = 'slug'


# @login_required
# def image_create(request):
#     if request.method == 'POST':
#         form = CreateImage(data=request.POST)
#         if form.is_valid():
#             new_image = form.save(commit=False)
#             new_image.user = request.user
#             new_image.save()
#             messages.success(request, 'Image added succesfully')
#             return render(request, 'images/image_detail.html')
#     else:
#         form = CreateImage(data=request.GET)
#     return render(request, 'images/image_form.html', {'form': form})
@method_decorator(login_required, name='dispatch')
class ImageCreate(CreateView):
    #permission_required = 'images.add_image'
    model = Image
    fields = ['title', 'picture', 'slug']
    success_url = '/gallery/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ImageDelete(DeleteView):
    #permission_required = 'images.delete_image'
    model = Image
    success_url = '/gallery/'
    template_name = 'images/image_confirm_delete.html'

templates/images/image_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete</title>
</head>
<body>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>
</body>
</html>

templates/images/image_detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Photo Detail</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo-style.css' %}">


</head>
<body>
    <!-- Page Loader -->
    <div id="loader-wrapper">
        <div id="loader"></div>

        <div class="loader-section section-left"></div>
        <div class="loader-section section-right"></div>

    </div>
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand" href="index.html">
                <i class="fas fa-film mr-2"></i>
                Album
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link nav-link-1 active" aria-current="page" href="/gallery">Photos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-link-2" href="/gallery/video">Videos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-link-3" href="/gallery/audio">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-link-4" href="/logout">Log Out</a>
                </li>
            </ul>
            </div>
        </div>
    </nav>


    <div class="container-fluid tm-container-content tm-mt-60">
        <div class="row mb-4">
            <h2 class="col-12 tm-text-primary">{{image.title}}</h2>
        </div>
        <div class="row tm-mb-90">            
            <div class="col-xl-8 col-lg-7 col-md-6 col-sm-12">
                <img src="{{image.picture.url}}" alt="Image" class="img-fluid">
            </div>
            <div class="col-xl-4 col-lg-5 col-md-6 col-sm-12">
                <div class="tm-bg-gray tm-video-details">
                    <div class="text-center mb-5">
                        <a href="{% url 'images:images_delete' image.id %}" class="btn btn-primary tm-btn-big">Delete</a>
                    </div>                    
                    <div class="mb-4 d-flex flex-wrap">
                        <div class="mr-4 mb-2">
                            <span class="tm-text-gray-dark">Dimension: </span><span class="tm-text-primary">1920x1080</span>
                        </div>
                        <div class="mr-4 mb-2">
                            <span class="tm-text-gray-dark">Format: </span><span class="tm-text-primary">JPG</span>
                        </div>
                    </div>
<!--                    <div>-->
<!--                        <h3 class="tm-text-gray-dark mb-3">Tags</h3>-->
<!--                        <a href="#" class="tm-text-primary mr-4 mb-2 d-inline-block">Cloud</a>-->
<!--                        <a href="#" class="tm-text-primary mr-4 mb-2 d-inline-block">Bluesky</a>-->
<!--                        <a href="#" class="tm-text-primary mr-4 mb-2 d-inline-block">Nature</a>-->
<!--                        <a href="#" class="tm-text-primary mr-4 mb-2 d-inline-block">Background</a>-->
<!--                        <a href="#" class="tm-text-primary mr-4 mb-2 d-inline-block">Timelapse</a>-->
<!--                        <a href="#" class="tm-text-primary mr-4 mb-2 d-inline-block">Night</a>-->
<!--                        <a href="#" class="tm-text-primary mr-4 mb-2 d-inline-block">Real Estate</a>-->
<!--                    </div>-->
                </div>
            </div>
        </div>
    </div> <!-- container-fluid, tm-container-content -->

    
    <script src="{% static 'js/plugins.js' %}"></script>
    <script>
        $(window).on("load", function() {
            $('body').addClass('loaded');
        });
    </script>
</body>
</html>

templates/images/image_form.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo-style.css' %}">
</head>

<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
<!--  <img src="{{ request.GET.url }}" class="image-preview">-->
    <input type="submit" value="Save">
</form>

</body>
</html>

templates/images/images.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gallery</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo-style.css' %}">
</head>

<body>
    <!-- Page Loader -->
    <div id="loader-wrapper">
        <div id="loader"></div>

        <div class="loader-section section-left"></div>
        <div class="loader-section section-right"></div>

    </div>
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand" href="/gallery">
                <i class="fas fa-film mr-2"></i>
                Album
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a href="image/create/" role="button" class="btn btn-primary">Add</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-link-1 active" aria-current="page" href="/gallery">Photos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-link-2" href="/gallery/video">Videos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-link-3" href="/gallery/audio">Audios</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-link-4" href="/account/logout">Log Out</a>
                </li>
            </ul>
            </div>
        </div>
    </nav>

    <div class="tm-hero d-flex justify-content-center align-items-center" data-parallax="scroll" data-image-src="img/hero.jpg">
        <form class="d-flex tm-search-form">
            <input class="form-control tm-search-input" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success tm-search-btn" type="submit">
                <i class="fas fa-search"></i>
            </button>
        </form>
    </div>

    <div class="container-fluid tm-container-content tm-mt-60">
        <div class="row mb-4">
            <h2 class="col-6 tm-text-primary">
                Latest Photos
            </h2>
            <div class="col-6 d-flex justify-content-end align-items-center">
                <form action="" class="tm-text-primary">
                    Page <input type="text" value="1" size="1" class="tm-input-paging tm-text-primary"> of 200
                </form>
            </div>
        </div>
        <div class="row tm-mb-90 tm-gallery">
            {% for image in image_list %}
        	<div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-12 mb-5">
                <figure class="effect-ming tm-video-item">
                    <img src="{{image.picture.url}}" alt="Image" class="img-fluid">
                    <figcaption class="d-flex align-items-center justify-content-center">
                        <h2>{{image.title}}</h2>
                        <a href="{% url 'images:images_detail' image.slug %}">View more</a>
                    </figcaption>                    
                </figure>
                <div class="d-flex justify-content-between tm-text-gray">
                    <span class="tm-text-gray-light">{{image.created}}</span>
                </div>
            </div>
            {% empty %}
            <h2>No objects yet.</h2>
            {% endfor %}
        </div> <!-- row -->
        <div class="row tm-mb-90">
            <div class="col-12 d-flex justify-content-between align-items-center tm-paging-col">
                <a href="javascript:void(0);" class="btn btn-primary tm-btn-prev mb-2 disabled">Previous</a>
                <div class="tm-paging d-flex">
                    <a href="javascript:void(0);" class="active tm-paging-link">1</a>
                    <a href="javascript:void(0);" class="tm-paging-link">2</a>
                    <a href="javascript:void(0);" class="tm-paging-link">3</a>
                    <a href="javascript:void(0);" class="tm-paging-link">4</a>
                </div>
                <a href="javascript:void(0);" class="btn btn-primary tm-btn-next">Next Page</a>
            </div>            
        </div>
    </div> <!-- container-fluid, tm-container-content -->

    
    <script src="{% static 'js/plugins.js' %}"></script>
    <script>
        $(window).on("load", function() {
            $('body').addClass('loaded');
        });
    </script>
</body>
</html>